**Import Libraries**

In [1]:
import pandas as pd
import numpy as np
import re
import string

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics import accuracy_score, classification_report

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier

import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

**Load Dataset**

In [7]:
df = pd.read_csv("IMDB Dataset.csv", engine='python', on_bad_lines='skip')

df.head()
df.shape
df['sentiment'].value_counts()

sentiment
positive    4757
negative    4707
Name: count, dtype: int64

In [8]:
print("Dataset Shape:", df.shape)
print("\nSample Data:")
display(df.head())

print("\nClass Distribution:")
print(df['sentiment'].value_counts())

Dataset Shape: (9464, 2)

Sample Data:

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

Class Distribution:
sentiment
positive    4757
negative    4707
Name: count, dtype: int64

In [9]:
import re
import string
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()

def preprocess(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)  # remove URLs
    text = re.sub(r"[^a-zA-Z]", " ", text)  # remove punctuation
    words = text.split()

    words = [word for word in words if word not in stop_words]
    words = [stemmer.stem(word) for word in words]

    return " ".join(words)

df['clean_text'] = df['review'].apply(preprocess)

In [10]:
df['sentiment'] = df['sentiment'].map({'positive':1, 'negative':0})

**Train-Test Split**

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df['clean_text'], df['sentiment'], test_size=0.2, random_state=42
)

**Feature Engineering**

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

**Model Training**

**LogisticRegression**

In [13]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(X_train_tfidf, y_train)

y_pred_lr = lr.predict(X_test_tfidf)

**Naive Bayes**

In [14]:
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()
nb.fit(X_train_tfidf, y_train)

y_pred_nb = nb.predict(X_test_tfidf)

**Decision Tree**

In [15]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt.fit(X_train_tfidf, y_train)

y_pred_dt = dt.predict(X_test_tfidf)

**Evaluation**

In [16]:
from sklearn.metrics import accuracy_score, classification_report

print("Logistic Regression")
print(accuracy_score(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

print("\nNaive Bayes")
print(accuracy_score(y_test, y_pred_nb))
print(classification_report(y_test, y_pred_nb))

print("\nDecision Tree")
print(accuracy_score(y_test, y_pred_dt))
print(classification_report(y_test, y_pred_dt))

Logistic Regression
0.8647649234020074
              precision    recall  f1-score   support

           0       0.89      0.83      0.86       954
           1       0.84      0.90      0.87       939

    accuracy                           0.86      1893
   macro avg       0.87      0.87      0.86      1893
weighted avg       0.87      0.86      0.86      1893


Naive Bayes
0.8515583729529846
              precision    recall  f1-score   support

           0       0.86      0.85      0.85       954
           1       0.85      0.86      0.85       939

    accuracy                           0.85      1893
   macro avg       0.85      0.85      0.85      1893
weighted avg       0.85      0.85      0.85      1893


Decision Tree
0.6967776016904385
              precision    recall  f1-score   support

           0       0.71      0.68      0.69       954
           1       0.69      0.71      0.70       939

    accuracy                           0.70      1893
   macro avg       0.70      0.70      0.70      1893
weighted avg       0.70      0.70      0.70      1893

**Comparison Table**

In [17]:
import pandas as pd
results = pd.DataFrame({
    "Model": ["Logistic Regression", "Naive Bayes", "Decision Tree"],
    "Accuracy": [
        accuracy_score(y_test, y_pred_lr),
        accuracy_score(y_test, y_pred_nb),
        accuracy_score(y_test, y_pred_dt)
    ]
})

results

                 Model  Accuracy
0  Logistic Regression  0.864765
1          Naive Bayes  0.851558
2        Decision Tree  0.696778

**Insights**

- TF-IDF performed better than BoW as it gives importance to important words.
- Logistic Regression gave the best performance.
- Naive Bayes worked well for text data.
- Decision Tree performed comparatively lower.
- Preprocessing improved model accuracy significantly.